name: Auto Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full commit history
          persist-credentials: false

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add Upstream & Fetch
        run: |
          git remote add upstream https://github.com/cdac-int-project/Community-Detection-In-Social-Network.git || true
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit

      - name: Push Changes to Fork
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
